language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: gKP49v0yoLxGQf1wTsv1cUyb7ZctCocrZM+DbOSKAarWFR6ORyGgVo99EKgVFd4bigUhfKdC/fOdDz2zbtuGNjBe+34uqbtmn3nsWh16y7EwLnS1nOUISBpy8lWjUBmeoCwsjDKYF+Pa7RHy7dlWZjFggwLcnfl56mGRIJbA6Zem4F2MwMMOVrmdytPmvHDUE2pVfDDwiDn5RhZbVPS9sGI5zRyAg5lguyN6LTcXkSgv8RNZ3CU7ow9kGueFTOSKK4uPNpdpBckbYaG5qqXzOX0QFSWc5dh1KtXWuWkfhQKbT2hLgEsg27xtuIiDqXDTc372tqul7ZHt2bsuJxFJcY/hEAiHLbbnLIQ1VwsBy/RTacBVCfnkGhbN5McP+tQ4EKXbv2VWDo1ZVVks7l2PyS91OPe+mWg+F1NA5BEKSZx5FD/TD+fgsRUSZmxp4QkhBVKj0c9qaVE/vuApv+U0JGCOEbxouOgNTEY1kdo7/UPAw2JwVTA9wg3IICn06b4A9aBK/Db/7XZPFpbmBCMMy//6ACIEHViDZPqqNlcg/1+FZ1AgQpCj6ZSivPZlMsFdoUPn3yguMqWf0bY+R/tksuCk8rAHuaJ9BJSCS3BhjkPN0p6uOgbPiVeFj37+d9DdBAcr358VjgxZclKKqMWy+aCTby5mehJAzbhmfyA/u5k=
  app: stark-mesa-53003
  on:
    all_branches: false
